CREATE USER '[[[.CDC_CONF_USER]]]'@'%' IDENTIFIED BY '[[[.CDC_CONF_PASSWORD]]]';
CREATE USER '[[[.CDC_CONF_USER]]]'@'localhost' IDENTIFIED BY '${CDC_CONF_PASSWORD}';

GRANT ALL ON maxwell.* TO '[[[.CDC_CONF_USER]]]'@'%';
GRANT ALL ON maxwell.* TO '[[[.CDC_CONF_USER]]]'@'localhost';

GRANT SELECT, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO '[[[.CDC_CONF_USER]]]'@'%';
GRANT SELECT, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO '[[[.CDC_CONF_USER]]]'@'localhost';